version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8181:8081"          # Attention : le port interne officiel de Nexus est 8081
    volumes:
      - devsecops_nexus-data:/nexus-data

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - devsecops_db_data:/var/lib/mysql

  springapp:
    build: .
    container_name: springapp
    depends_on:
      - mysqldb
    ports:
      - "8001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/demo
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  devsecops_nexus-data:
    external: true
  devsecops_db_data:
    external: false  # ici volume local géré par Docker-compose
